version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: t2r_db_container
    environment:
      - POSTGRES_USER=t2r_admin
      - POSTGRES_PASSWORD=t2r_secret
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: